/* Folds the edited words from the site_copy table into public/*.html, on the
   build, just before Netlify publishes. The site stays plain static HTML: no
   script on the page, no function in front of it, nothing to pay for per
   visitor, and a search engine reads the same words a parent does.

     npm run copy                     # rewrite netlify/lib/copy-fields.js from the pages
     node scripts/copy.mjs --check    # is that file still in step? (npm test refuses a stale one)
     node scripts/copy.mjs --apply    # fold the saved edits in (runs on every deploy)

   netlify/lib/copy-fields.js is generated and committed, the way the CSP hashes
   in netlify.toml are: the editor runs in a bundled function that cannot read
   public/index.html, so the list of editable strings has to travel with it.

   A deploy with no database URL, or a database that cannot be reached, leaves
   the pages exactly as they are committed. The words on the site are never
   worse than what is in git. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PAGES, applyCopy, fields, stripMarks } from '../netlify/lib/copy.js';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const pagePath = (p) => path.join(ROOT, 'public', p);

const FIELDS_FILE = path.join(ROOT, 'netlify', 'lib', 'copy-fields.js');

/* every data-copy name parses, is unique, and is shaped page.section.thing */
export function readFields() {
  const out = [];
  for (const p of PAGES) out.push(...fields(fs.readFileSync(pagePath(p), 'utf8'), p));
  return out;
}

export function fieldsFile(list) {
  return `/* Generated by \`npm run copy\` from the data-copy names in public/*.html.
   Do not edit by hand: change the wording in the page, then run npm run copy.
   The editor at /admin/copy runs as a bundled function with no access to the
   published files, so the list of editable strings has to travel with it. */
export const FIELDS = ${JSON.stringify(list, null, 2)};
`;
}

export function applyTo(overrides, log = () => {}) {
  let changed = 0;
  for (const p of PAGES) {
    const file = pagePath(p);
    const html = fs.readFileSync(file, 'utf8');
    const edited = applyCopy(html, overrides);
    /* the data-copy names travel no further than the build */
    const out = stripMarks(edited);
    fs.writeFileSync(file, out);
    if (edited !== html) changed++;
    log(`copy: ${p} ${edited === html ? 'as committed' : 'rewritten'}, names stripped`);
  }
  return changed;
}

if (process.argv[1] && process.argv[1].endsWith('copy.mjs')) {
  if (process.argv.includes('--check')) {
    const wanted = fieldsFile(readFields());
    const have = fs.existsSync(FIELDS_FILE) ? fs.readFileSync(FIELDS_FILE, 'utf8') : '';
    if (have !== wanted) { console.error('netlify/lib/copy-fields.js is out of step with public/index.html — run `npm run copy`'); process.exit(1); }
    console.log('copy: the list of editable strings is up to date'); process.exit(0);
  }
  if (!process.argv.includes('--apply')) {
    const list = readFields();
    fs.writeFileSync(FIELDS_FILE, fieldsFile(list));
    console.log(`copy: wrote netlify/lib/copy-fields.js with ${list.length} editable strings`); process.exit(0);
  }
  /* --apply, on the deploy: nothing here may throw, so the parsing that would
     is left to --check, which the tests run on every commit */
  const { databaseUrl } = await import('../netlify/lib/db.js');
  const url = databaseUrl();
  let overrides = {};
  if (!url) console.log('copy: this context has no database URL, the committed wording it is');
  else {
    try {
      const { neon } = await import('@neondatabase/serverless');
      const rows = await neon(url)`SELECT key, value FROM site_copy`;
      overrides = Object.fromEntries(rows.map(r => [r.key, r.value]));
      console.log(`copy: ${rows.length} edited string(s) from the database`);
    } catch (e) {
      /* an unreachable database, or the table not yet migrated, must never fail
         a deploy: the committed wording is a perfectly good site */
      console.log('copy: could not read site_copy (' + e.message + '); the committed wording it is');
    }
  }
  try { applyTo(overrides, console.log); }
  catch (e) { console.log('copy: could not rewrite the pages (' + e.message + '); publishing them as committed'); }
}
