/* Generated by `npm run copy` from the data-copy names in public/*.html.
   Do not edit by hand: change the wording in the page, then run npm run copy.
   The editor at /admin/copy runs as a bundled function with no access to the
   published files, so the list of editable strings has to travel with it. */
export const FIELDS = [
  {
    "key": "home.meta.title",
    "label": "The title in Google and the browser tab",
    "note": "The blue line in a Google result and the name of the browser tab. Aim for under 60 characters.",
    "page": "index.html",
    "plain": true,
    "tags": [],
    "original": "Lunch Sorted — a week of school lunches in about a minute"
  },
  {
    "key": "home.meta.description",
    "label": "The description in Google",
    "note": "The grey lines under the title in a Google result. Around 150 characters.",
    "page": "index.html",
    "plain": true,
    "tags": [],
    "original": "Answer three questions and get a week of packed school lunches, matched so each box goes together, with the shopping list built for you. Free, works offline, nothing to install."
  },
  {
    "key": "home.meta.share-title",
    "label": "The heading on a shared link",
    "note": "The heading on the card when someone shares the link in a message, on Facebook or in a group.",
    "page": "index.html",
    "plain": true,
    "tags": [],
    "original": "Lunch Sorted"
  },
  {
    "key": "home.meta.share-text",
    "label": "The words on a shared link",
    "note": "The line under the heading on that shared card.",
    "page": "index.html",
    "plain": true,
    "tags": [],
    "original": "A week of packed school lunches in about a minute — matched boxes, school rules respected, shopping list built for you."
  },
  {
    "key": "home.nav.cta",
    "label": "The button at the top of the page",
    "note": "The button at the top right of the page.",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Open the planner"
  },
  {
    "key": "home.hero.title",
    "label": "The headline",
    "note": "The first thing a parent reads.",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Lunch, sorted. A week of school lunches in about a minute."
  },
  {
    "key": "home.hero.lede",
    "label": "The paragraph under the headline",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Answer three questions — what can go in the box, what has to stay out, how picky they are — and Lunch Sorted builds the week, matches what goes with what, and hands you the shopping list."
  },
  {
    "key": "home.hero.cta",
    "label": "The green button",
    "note": "The main green button. Short: it has to fit on a phone.",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Plan this week — free"
  },
  {
    "key": "home.hero.cta-second",
    "label": "The second button",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "See how it works"
  },
  {
    "key": "home.hero.free",
    "label": "The small line under the buttons",
    "note": "The small capitals under the buttons.",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Free to plan · everything on for your first three weeks · no card, no account needed"
  },
  {
    "key": "home.how.eyebrow",
    "label": "Section label: how it works",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "How it works"
  },
  {
    "key": "home.how.title",
    "label": "Section heading: how it works",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Three taps, then a plan you can shop from."
  },
  {
    "key": "home.how.intro",
    "label": "The paragraph under that heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "No blank screen, no setting up a database of your child's food before you get anything back."
  },
  {
    "key": "home.how.one-title",
    "label": "Step one: heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Tell it the rules"
  },
  {
    "key": "home.how.one-text",
    "label": "Step one: the words",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Cold only or is there a microwave. Nut-free, dairy-free, whatever your school and your kid need."
  },
  {
    "key": "home.how.two-title",
    "label": "Step two: heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "It draws the week"
  },
  {
    "key": "home.how.two-text",
    "label": "Step two: the words",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "A main, side, fruit and sweet for every pack day, arranged so each box actually works together."
  },
  {
    "key": "home.how.three-title",
    "label": "Step three: heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Shop, then pack"
  },
  {
    "key": "home.how.three-text",
    "label": "Step three: the words",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "One shopping list grouped by aisle. Each morning, a checklist of exactly what goes in the bag."
  },
  {
    "key": "home.what.eyebrow",
    "label": "Section label: what's in it",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "What's in it"
  },
  {
    "key": "home.what.title",
    "label": "Section heading: what's in it",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Four jobs."
  },
  {
    "key": "home.what.main-label",
    "label": "Green compartment: the small word",
    "note": "The small coloured word above the heading.",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Main"
  },
  {
    "key": "home.what.main-title",
    "label": "Green compartment: heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "It knows what goes together"
  },
  {
    "key": "home.what.main-text",
    "label": "Green compartment: the words",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Not a random draw. Crunch against a soft main, protein when the main is light, something tangy to cut the salt — and it tells you why each box was built that way. Tell it what came home uneaten and next week’s draw leans toward what actually gets eaten."
  },
  {
    "key": "home.what.side-label",
    "label": "Orange compartment: the small word",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Side"
  },
  {
    "key": "home.what.side-title",
    "label": "Orange compartment: heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Your school's rules, respected"
  },
  {
    "key": "home.what.side-text",
    "label": "Orange compartment: the words",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Nut-free, seed-free, dairy-free, cold-only, no ice pack, a short eating window, no chocolate — plus anything else you list. Excluded foods are flagged in your list, never silently dropped, so you always know why something stopped appearing. Add a snack or drink compartment if your school day needs one."
  },
  {
    "key": "home.what.fruit-label",
    "label": "Pink compartment: the small word",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Fruit"
  },
  {
    "key": "home.what.fruit-title",
    "label": "Pink compartment: heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The shopping list writes itself"
  },
  {
    "key": "home.what.fruit-text",
    "label": "Pink compartment: the words",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Every planned box rolls into one list grouped by aisle, with quantities. Tick off what the pantry already has and shop the rest. More than one kid? One list covers them all."
  },
  {
    "key": "home.what.sweet-label",
    "label": "Purple compartment: the small word",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Sweet"
  },
  {
    "key": "home.what.sweet-title",
    "label": "Purple compartment: heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Mornings become a checklist — and kids get a say"
  },
  {
    "key": "home.what.sweet-text",
    "label": "Purple compartment: the words",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The next school day as a checklist, with a flag when the box needs an ice pack, a sealed container, or is missing any protein. The night before, hand them the phone: the week's boxes, all inside your rules and already shopped for, and they tap the one they want. A lunch they chose tends to come home emptier."
  },
  {
    "key": "home.phone.eyebrow",
    "label": "Section label: on your phone",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "On your phone"
  },
  {
    "key": "home.phone.title",
    "label": "Section heading: on your phone",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Built for standing at the kitchen counter."
  },
  {
    "key": "home.phone.intro",
    "label": "The paragraph under that heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Designed at phone size first, because that's where lunch actually gets planned."
  },
  {
    "key": "home.phone.cap-week",
    "label": "Caption under the first screenshot",
    "note": "The caption under the first screenshot.",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The week"
  },
  {
    "key": "home.phone.cap-list",
    "label": "Caption under the second screenshot",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The list"
  },
  {
    "key": "home.phone.cap-morning",
    "label": "Caption under the third screenshot",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The morning"
  },
  {
    "key": "home.phone.cap-kid",
    "label": "Caption under the fourth screenshot",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The kid’s pick"
  },
  {
    "key": "home.install.eyebrow",
    "label": "Section label: install it",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Install it"
  },
  {
    "key": "home.install.title",
    "label": "Section heading: install it",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "It can live on your home screen."
  },
  {
    "key": "home.install.intro",
    "label": "The paragraph under that heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "There is no app to download. Add it to your home screen and it opens full-screen with its own icon, works with no signal, and keeps everything on the device."
  },
  {
    "key": "home.install.iphone",
    "label": "The iPhone step",
    "note": "Bold is allowed here: write it as <b>iPhone:</b>.",
    "page": "index.html",
    "plain": false,
    "tags": [
      "b"
    ],
    "original": "<b>iPhone:</b> open the planner in Safari, tap Share, then <b>Add to Home Screen</b>."
  },
  {
    "key": "home.install.android",
    "label": "The Android step",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [
      "b"
    ],
    "original": "<b>Android:</b> open it in Chrome, tap the menu, then <b>Install app</b>."
  },
  {
    "key": "home.install.after",
    "label": "The step after that",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Open it from the icon after that — installed, it holds onto your plans far more reliably than a browser tab."
  },
  {
    "key": "home.price.eyebrow",
    "label": "Section label: what it costs",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "What it costs"
  },
  {
    "key": "home.price.title",
    "label": "Section heading: what it costs",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Free to plan. Everything on for your first three weeks."
  },
  {
    "key": "home.price.intro",
    "label": "The paragraph under that heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Every new household gets the whole Household plan for three weeks, with no card and nothing to cancel. After that the planner stays free, and the rest is yours whenever you want it."
  },
  {
    "key": "home.price.free-label",
    "label": "Free plan: the small heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Free, for good"
  },
  {
    "key": "home.price.free-amount",
    "label": "Free plan: the price",
    "note": "Changing a price here changes the words on the page, never what Stripe charges. Change Stripe first.",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "$0"
  },
  {
    "key": "home.price.free-one",
    "label": "Free plan: first point",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "One lunchbox"
  },
  {
    "key": "home.price.free-two",
    "label": "Free plan: second point",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The week planned in a minute, matched so each box goes together"
  },
  {
    "key": "home.price.free-three",
    "label": "Free plan: third point",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The shopping list and the pack list"
  },
  {
    "key": "home.price.free-four",
    "label": "Free plan: fourth point",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Works offline, on your home screen"
  },
  {
    "key": "home.price.paid-label",
    "label": "Household plan: the small heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Household plan"
  },
  {
    "key": "home.price.paid-amount",
    "label": "Household plan: the price",
    "note": "Changing a price here changes the words on the page, never what Stripe charges. Change Stripe first.",
    "page": "index.html",
    "plain": false,
    "tags": [
      "small"
    ],
    "original": "$29 <small>a year</small>"
  },
  {
    "key": "home.price.paid-alt",
    "label": "Household plan: the other prices",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "or $3.99 a month, or $79 once, forever"
  },
  {
    "key": "home.price.paid-one",
    "label": "Household plan: first point",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Every lunchbox, each with its own rules"
  },
  {
    "key": "home.price.paid-two",
    "label": "Household plan: second point",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Kid’s pick, the morning review, a pantry that remembers"
  },
  {
    "key": "home.price.paid-three",
    "label": "Household plan: third point",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The other parent’s phone, and a helper’s pack list"
  },
  {
    "key": "home.price.paid-four",
    "label": "Household plan: fourth point",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Cancel any time; what you added stays"
  },
  {
    "key": "home.price.cta",
    "label": "The green button under the plans",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Start free"
  },
  {
    "key": "home.price.fine",
    "label": "The small print under the plans",
    "note": "This promises the refund window and links to the terms; terms.html has to agree with whatever it says.",
    "page": "index.html",
    "plain": false,
    "tags": [
      "a"
    ],
    "original": "Prices in US dollars; sales tax added where it applies. Full refund within 14 days, no questions. <a href=\"/terms.html\">Terms</a>."
  },
  {
    "key": "home.next.eyebrow",
    "label": "Section label: what's coming",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "What's coming"
  },
  {
    "key": "home.next.title",
    "label": "Section heading: what's coming",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "The iPhone app, and a reminder the night before."
  },
  {
    "key": "home.next.intro",
    "label": "The paragraph under that heading",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Two parents' phones already share one plan. Next is an app on the App Store with a Home Screen widget and an evening nudge to pack. Leave an email if you want to hear when it lands; that's the only thing this page collects, and it's used for nothing else."
  },
  {
    "key": "home.next.cta",
    "label": "The button on the email form",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Keep me posted"
  },
  {
    "key": "home.footer.line",
    "label": "The line at the bottom of the page",
    "note": "",
    "page": "index.html",
    "plain": false,
    "tags": [],
    "original": "Lunch Sorted — a Lila Bloom Enterprises project"
  }
];
